run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  govet:
    enable-all: true
    disable:
      - shadow
  
  revive:
    rules:
      - name: exported
        disabled: true
  
  gosec:
    excludes:
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
